In [45]:
import pandas as pd
import numpy as np
import math
import scipy.linalg as la
from datetime import datetime

In [24]:
significant_digits = 4
matrix_num_cols = 10000
matrix_num_row = 10000

In [10]:
round_to_sig_digits = lambda x: round(x, significant_digits - int(math.floor(math.log10(abs(x)))) - 1) if x != 0 else 0
v_round_to_sig_digits = np.vectorize(round_to_sig_digits)

In [34]:
# matrix = np.random.randint(10, 90, (matrix_num_row, matrix_num_cols))
matrix = significant_digits * np.random.randn(matrix_num_row, matrix_num_cols)
matrix = v_round_to_sig_digits(matrix)
B = np.random.randint(10, 90, (matrix_num_row, 1))

print(matrix.shape, B.shape)

(10000, 10000) (10000, 1)


In [35]:
matrix[[0, 1]]

array([[-1.315 , -1.084 ,  4.217 , ...,  5.662 ,  2.07  , -9.362 ],
       [-0.2808, -5.056 , -3.527 , ..., 10.42  , -3.515 ,  1.224 ]])

In [19]:
(_, rref) = la.qr(matrix) # perform QR decomposition, R is RREF

In [20]:
rref

array([[ 4.00609720e+02, -1.97485140e+00, -3.53285571e-01, ...,
        -2.90698589e+00, -2.30051125e+00, -1.36349294e+00],
       [ 0.00000000e+00, -4.05159195e+02,  1.03443088e+00, ...,
        -2.59315561e+00, -4.39125322e+00,  3.34362222e+00],
       [ 0.00000000e+00,  0.00000000e+00,  4.06869475e+02, ...,
        -1.56660511e+00,  2.49890271e+00, -1.17475920e+00],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -3.45426486e+00, -3.66618668e+00,  9.60207779e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00, -8.76940898e+00,  3.08339928e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  4.36456878e+00]])

In [37]:
X = np.linalg.solve(matrix, B)

In [40]:
X

array([[10.36096763],
       [-7.70020666],
       [ 3.43587494],
       ...,
       [13.71204765],
       [ 2.82283655],
       [-9.56855692]])

In [48]:
def gauss_solve(A, b):
    
    #Concontanate the matrix A and right hand side column 
    #vector b into one matrix
    temp_mat = np.c_[A, b]
    
    #Get the number of rows
    n = temp_mat.shape[0]
    
    #Loop over rows
    for i in range(n):
        print(f"REF Processing for ROW -- {i}, time - {datetime.now()}")
            
        #Find the pivot index by looking down the ith 
        #column from the ith row to find the maximum 
        #(in magnitude) entry.
        p = np.abs(temp_mat[i:, i]).argmax()
            
        #We have to reindex the pivot index to be the 
        #appropriate entry in the entire matrix, not 
        #just from the ith row down.
        p += i 
    
        #Swapping rows to make the maximal entry the 
        #pivot (if needed).
        if p != i:
            temp_mat[[p, i]] = temp_mat[[i, p]]
            
        #Eliminate all entries below the pivot
        factor = temp_mat[i+1:, i] / temp_mat[i, i]
        temp_mat[i+1:] -= factor[:, np.newaxis] * temp_mat[i]
                
    #Allocating space for the solution vector
    x = np.zeros_like(b, dtype=np.double);

    #Here we perform the back-substitution.  Initializing 
    #with the last row.
    x[-1] = temp_mat[-1,-1] / temp_mat[-1, -2]
    
    #Looping over rows in reverse (from the bottom up), starting with the second to
    #last row, because the last row solve was completed in the last step.
    for i in range(n-2, -1, -1):
        print(f"BACK SUBSITUTION Processing for ROW -- {i}, time - {datetime.now()}")
        x[i] = (temp_mat[i,-1] - np.dot(temp_mat[i,i:-1], x[i:])) / temp_mat[i,i]
        
    return x

In [49]:
p = gauss_solve(matrix, B)

REF Processing for ROW -- 0, time - 2021-08-28 00:03:56.357384
REF Processing for ROW -- 1, time - 2021-08-28 00:03:56.927614
REF Processing for ROW -- 2, time - 2021-08-28 00:03:57.497069
REF Processing for ROW -- 3, time - 2021-08-28 00:03:58.069363
REF Processing for ROW -- 4, time - 2021-08-28 00:03:58.660183
REF Processing for ROW -- 5, time - 2021-08-28 00:03:59.192207
REF Processing for ROW -- 6, time - 2021-08-28 00:03:59.723932
REF Processing for ROW -- 7, time - 2021-08-28 00:04:00.273592
REF Processing for ROW -- 8, time - 2021-08-28 00:04:00.811309
REF Processing for ROW -- 9, time - 2021-08-28 00:04:01.372924
REF Processing for ROW -- 10, time - 2021-08-28 00:04:01.917706
REF Processing for ROW -- 11, time - 2021-08-28 00:04:02.488780
REF Processing for ROW -- 12, time - 2021-08-28 00:04:03.032005
REF Processing for ROW -- 13, time - 2021-08-28 00:04:03.577771
REF Processing for ROW -- 14, time - 2021-08-28 00:04:04.119197
REF Processing for ROW -- 15, time - 2021-08-28 00

In [50]:
p

array([[10.36096763],
       [-7.70020666],
       [ 3.43587494],
       ...,
       [13.71204765],
       [ 2.82283655],
       [-9.56855692]])