# Gauss elimination method without partial pivoting

In [1]:
import pandas as pd
import numpy as np

In [2]:
# n
matrix_num_row = 2
matrix_num_cols = 2

In [3]:
matrix = np.zeros(shape=(matrix_num_row, matrix_num_cols))

In [4]:
matrix

array([[0., 0.],
       [0., 0.]])

In [5]:
b = np.zeros(shape=(matrix_num_row, 1))
b

array([[0.],
       [0.]])

## User Input for (nxn) matrix

In [6]:
significant_digits = 4
#TODO significant_digits = int(input(f"significant_digits = "))

In [7]:
for i in range(0, matrix_num_row):
    for j in range(0, matrix_num_cols):
        #print(f"{i} {j}")
        element = int(input(f"enter elements of Matrix A[{i}{j}]"))
        matrix[i][j] = element

In [8]:
for i in range(0, matrix_num_row):
    element = int(input(f"enter elements of b[{i}]"))
    b[i] = element

In [9]:
matrix

array([[2., 1.],
       [3., 2.]])

In [10]:
b

array([[7.],
       [5.]])

## REF Calculation

In [11]:
for i in range(0, matrix_num_row - 1):
    m = matrix[i+1][i] / matrix[i][i] #TODO roundoff 
    print(m)
    matrix[i+1][i] = matrix[i+1][i] - (m * matrix[i][i])
    matrix[i+1][i+1] = matrix[i+1][i+1] - (m * matrix[i][i+1]) # operating the 2nd col
    b[i+1] = b[i+1] - m * b[i]

1.5


In [12]:
matrix

array([[2. , 1. ],
       [0. , 0.5]])

In [13]:
b

array([[ 7. ],
       [-5.5]])

## Back Substitution

In [14]:
x = np.zeros(matrix_num_row)
for i in range(matrix_num_row - 1, -1, -1):
        x[i] = (b[i] - np.dot(matrix[i,i+1:],x[i+1:]))/matrix[i,i]


In [15]:
matrix

array([[2. , 1. ],
       [0. , 0.5]])

In [16]:
b

array([[ 7. ],
       [-5.5]])

In [17]:
x

array([  9., -11.])

In [18]:
np.random.rand(2, 2)


array([[0.90367822, 0.78985287],
       [0.14640164, 0.46617721]])