# Gauss elimination method without partial pivoting

Ax = b

In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
# n
matrix_num_row = 2
matrix_num_cols = 2

## User Input for significant digit

In [3]:
#TODO significant_digits = int(input(f"significant_digits = "))
significant_digits = int(input(f"enter significant digit for calculation"))
print(f"significant digits from user input is {significant_digits}")

significant digits from user input is 2


In [4]:
round_to_sig_digits = lambda x: round(x, significant_digits - int(math.floor(math.log10(abs(x)))) - 1) if x != 0 else 0
v_round_to_sig_digits = np.vectorize(round_to_sig_digits)

## Generate a random 2x2 matrix

In [5]:
# rand_matrix = np.random.randint(10,90,(matrix_num_row, matrix_num_cols))
matrix = significant_digits * np.random.randn(matrix_num_row, matrix_num_cols)
matrix = v_round_to_sig_digits(matrix)
matrix

array([[ 2.4,  1.2],
       [-2. ,  1.1]])

In [6]:
b = significant_digits * np.random.randn(matrix_num_row, 1)
#rand_b = np.random.randint(1, 20, (matrix_num_row, 1))
b = v_round_to_sig_digits(b)
b

array([[-0.78],
       [-0.8 ]])

## Partial Pivoting, to ensure correctness in the solution

In [7]:
if abs(matrix[0][0]) < abs(matrix[1][0]): # swap rows
    print("partial pivoting is required")
    matrix[[0,1]] = matrix[[1,0]]
    b[[0,1]] = b[[1,0]]
else:
    print("partial pivoting is not required")

print(matrix)
print(b)


partial pivoting is not required
[[ 2.4  1.2]
 [-2.   1.1]]
[[-0.78]
 [-0.8 ]]


## REF Calculation

In [8]:
# DO this until REF is reached
for i in range(0, matrix_num_row - 1):
    m = matrix[i+1][i] / matrix[i][i] #TODO roundoff, consistent matrix
    print(m)
    matrix[i+1][i] = matrix[i+1][i] - (m * matrix[i][i])
    matrix[i+1][i+1] = matrix[i+1][i+1] - (m * matrix[i][i+1]) # operating the 2nd col
    b[i+1] = b[i+1] - m * b[i]

-0.8333333333333334


In [9]:
matrix

array([[2.4, 1.2],
       [0. , 2.1]])

In [10]:
matrix = v_round_to_sig_digits(matrix)
matrix

array([[2.4, 1.2],
       [0. , 2.1]])

In [11]:
b = v_round_to_sig_digits(b)
b

array([[-0.78],
       [-1.5 ]])

## Back Substitution

In [12]:
x = np.zeros(matrix_num_row)
for i in range(matrix_num_row - 1, -1, -1):
        x[i] = (b[i] - np.dot(matrix[i,i+1:],x[i+1:]))/matrix[i,i]
x = v_round_to_sig_digits(x) #considering only significant digits

## Solution for X1 and X2

In [13]:
x


array([ 0.032, -0.71 ])

In [17]:
df = pd.DataFrame(data = x, index = ['x1', 'x2'], columns=['solution'])

In [18]:
df

solution
x1     0.032
x2    -0.710